name: General CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  no-scheduling:
    runs-on: ubuntu-latest
    steps:
      - name: Delay scheduling of jobs
        run: sleep 10

  v-compiles-sdl-examples:
    runs-on: ubuntu-18.04
    needs: no-scheduling
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout sdl
        run: |
          git clone --depth 1 https://github.com/vlang/sdl
          cd sdl
          mkdir -p ~/.vmodules
          ln -s $(pwd) ~/.vmodules/sdl

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libsdl2-dev libsdl2-ttf-dev
          sudo apt-get install --quiet -y libsdl2-mixer-dev libsdl2-image-dev

      - name: Build local v
        run: make

      - name: Test code formatting
        run: |
          cd sdl
          ../v test-fmt

      - name: Build sdl shared
        run: ./v -shared -g sdl

      - name: Run tests
        run: ./v test sdl

      - name: Build sdl examples
        run: |
          for example in basic_window tvintris; do
              epath=examples/$example;
              echo $epath;
              v "$epath";
          done
